version: "3.7"

services:
  item-app:
    container_name: item-app
    image: ghcr.io/radearsr/item-app:v1
    ports:
      - 80:8080
    environment:
      NODE_ENV: production
      DB_HOST: item-db
    depends_on:
      - item-db
    restart: on-failure
  item-db:
    container_name: item-db
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin

volumes:
  app-db:
    name: app-db
    